### ISSUE TITLE
plugins / modules / extensions system

### ISSUE THREAD

**Issue by braid-sync** [braidchat/planning#194]
I'd like to see Braid have some sort of module/plugin-like system to make it an actual "platform" for group chat. 

Analogies:
  - Chrome extensions
  - Wordpress plugins
  - Drupal modules
  - WeChat apps

Note: I'm envisioning a much deeper integration than a websocket or REST API

Examples that could be plugins:
  - custom emoticons
  - [reactions / likes / hearts](https://github.com/braidchat/planning/issues/250)
  - existing "quests" system (https://github.com/braidchat/planning/issues/280)
  - various other oauth services
  - integrations with custom UI ([slack](https://github.com/braidchat/planning/issues/135), github, [asana](https://github.com/braidchat/planning/issues/137), [email](https://github.com/braidchat/planning/issues/191),  etc.) 
  - [auto-translate](https://github.com/braidchat/planning/issues/270)
  - different file saving ([dropbox](https://github.com/braidchat/planning/issues/136), box, [bittorrent sync](https://github.com/braidchat/planning/issues/284), [aerofs](https://github.com/braidchat/planning/issues/285)etc. )
  - [various auto-complete integrations](https://github.com/braidchat/planning/issues/228)
  - various link extraction integrations (ex. spotify, soundclould, etc.)
  - [voice and video chat](https://github.com/braidchat/planning/issues/149)

Benefits:
  - existing code organization can be greatly improved
  - easy for others to extend Braid without mucking up the core

Considerations:
  - plugins can affect backend and frontend (across devices)
  - admins can add / enable certain plugins for their users (ideally, make it super easy, in-app, 1-click; like wordpress plugin installation)
  - users can enable certain plugins for themselves (maybe)

Open questions:
 - how to do "plugins" in clojure apps?
    - http://stackoverflow.com/questions/17969926/architecture-for-plugins-to-be-loaded-in-runtime
     - http://stackoverflow.com/questions/10272559/how-best-to-structure-and-build-clojure-apps-with-plugins

 - how to do "hooks" in clojure?
     - https://github.com/technomancy/robert-hooke

**Comment by braid-sync** [comment]
➤ Rafal Dittwald commented:
no - at least, not yet - don't want to be tainted by the slack way of doing things - let's invent something better first - worry about this issue later

[--- Commented from GitHub.com
#commenter pkobrien
---[gh]

**Comment by braid-sync** [comment]
➤ Rafal Dittwald commented:
Agreed. 

The Asana <-> Github sync of tasks lost all sense of ordering. Will fix with tags soon.

On January 11, 2016 at 11:57:34 AM, pkobrien (notifications@github.com) wrote:

no - at least, not yet - don't want to be tainted by the slack way of doing things - let's invent something better first - worry about this issue later

—
Reply to this email directly or view it on GitHub.

[--- Commented from GitHub.com
#commenter rafd
---[gh]

**Comment by rafd** [comment]
Thoughts re: implementation:
  - hooks / events are likely to play a big role  (ie. braid core dispatches events at various times that can be hooked into) ; are there alternative architectures?
  - can do this in phases:
       1. all plugins are still part of core project, just namespaced (already kind of doing, but without good core hook/event infrastructure)
       2. plugins migrate to clojar libraries (Braid core has all plugins as dependencies)
       3. a way to download + load the necessary plugin code at runtime
