### ISSUE TITLE
allow for plugins (separate from integrations)

### ISSUE THREAD

**Issue by braid-sync** [braidchat/planning#249]
we want braid to be a platform

ideally, should have a way for devs to write plugins that work cross-client

plugins would mostly be in-client (may need to think if they require server)

hosts can enable certain plugins for their users

users can enable certain plugins for their clients

for example:
 /giphy search
 custom emoticons

**Comment by braid-sync** [comment]
➤ Rafal Dittwald commented:
defer this for as long as possible if there is any chance that it interferes with refactoring core concepts until we get them worked out - early dev needs lots of experimenting and a plugin architecture could impede that as it implies a stable api somewhere

[--- Commented from GitHub.com
#commenter pkobrien
---[gh]

**Comment by rafd** [comment]
Merging this with: https://github.com/braidchat/planning/issues/194
