### ISSUE TITLE
use re-frame interceptor to validate app-state after db changes

### ISSUE THREAD

**Issue by braid-sync** [braidchat/planning#273]
Created by octocat bot on behalf of jamesnvc from [braid chat](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/57def626-3a26-46ec-aa43-f1eba4264509)

**Comment by braid-sync** [comment]
➤ Braid Sync Bot commented:
jamesnvc commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/15a55192-adc0-43db-bf91-96e5ad89ad67):
In the same way that our `transact!` function was working previously

[--- Commented from GitHub.com
#commenter braid-sync
---[gh]

**Comment by rafd** [comment]
Fixed by: https://github.com/braidchat/braid/commit/f2539c831fa99867d1f663da0a2aac145857ae5f
