### ISSUE TITLE
upgrade http-kit for JDK 9

### ISSUE THREAD

**Issue by tirkarthi** [braidchat/planning#410]
It seems that braid uses a version of http-kit that is incompatible with JDK 9 and above. It is fixed upstream and upgrading it will help in JDK 9 compatibility.

Relevant http-kit upstream issue : https://github.com/http-kit/http-kit/issues/356
Relevant release : https://github.com/http-kit/http-kit/releases/tag/2.3.0-beta2
Latest RC release : https://github.com/http-kit/http-kit/releases/tag/v2.3.0-RC1

It seems to be the similar case with Clojurescript and it's fixed in the 1.10 release .

This was reported using Clojars metadata and GitHub search. Feel free to close this if it's irrelevant.

**Comment by rafd** [comment]
Fixed as of https://github.com/braidchat/braid/commit/00e193
